package com.fittracksa.app.ui

import com.fittracksa.app.data.preferences.UserSettings

data class AppStrings(
    val loginTitle: String,
    val emailLogin: String,
    val googleSso: String,
    val biometric: String,
    val biometricSubtitle: String,
    val biometricUnavailable: String,
    val biometricFailed: String,
    val register: String,
    val forgotPassword: String,
    val dashboard: String,
    val activity: String,
    val nutrition: String,
    val progress: String,
    val settings: String,
    val achievements: String,
    val logActivity: String,
    val logMeal: String,
    val viewStreaks: String,
    val refresh: String,
    val selectType: String,
    val setDuration: String,
    val saveActivity: String,
    val cancel: String,
    val addFood: String,
    val useShortcut: String,
    val saveMeal: String,
    val editDelete: String,
    val weeklyMonthly: String,
    val filterRange: String,
    val viewDetails: String,
    val viewBadge: String,
    val joinChallenge: String,
    val seeStreakDetails: String,
    val languageToggle: String,
    val notifications: String,
    val manageData: String,
    val signOut: String,
    val darkMode: String,
    val profileSectionTitle: String,
    val profileNameLabel: String,
    val profileEmailPlaceholder: String,
    val changePhoto: String,
    val removePhoto: String,
    val saveProfile: String
)

fun stringsFor(language: UserSettings.Language): AppStrings = when (language) {
    UserSettings.Language.ENGLISH -> AppStrings(
        loginTitle = "Welcome to FitTrack SA",
        emailLogin = "Email Login",
        googleSso = "Google Sign-In",
        biometric = "Biometric Unlock",
        biometricSubtitle = "Use fingerprint or face to continue",
        biometricUnavailable = "Biometric authentication unavailable",
        biometricFailed = "Biometric match failed",
        register = "Register",
        forgotPassword = "Forgot Password",
        dashboard = "Dashboard",
        activity = "Activity",
        nutrition = "Nutrition",
        progress = "Progress",
        settings = "Settings",
        achievements = "Achievements",
        logActivity = "Log Activity",
        logMeal = "Log Meal",
        viewStreaks = "View Streaks/Achievements",
        refresh = "Refresh/Sync",
        selectType = "Select Type",
        setDuration = "Set Duration",
        saveActivity = "Save Activity",
        cancel = "Cancel",
        addFood = "Add Food",
        useShortcut = "Use Shortcut",
        saveMeal = "Save Meal",
        editDelete = "Edit/Delete Entry",
        weeklyMonthly = "Weekly/Monthly Toggle",
        filterRange = "Filter Range",
        viewDetails = "View Details",
        viewBadge = "View Badge",
        joinChallenge = "Join Challenge",
        seeStreakDetails = "See Streak Details",
        languageToggle = "Language Toggle (EN/ZU)",
        notifications = "Notifications On/Off",
        manageData = "Manage Data",
        signOut = "Sign Out",
        darkMode = "Theme (Dark/Light)",
        profileSectionTitle = "Profile",
        profileNameLabel = "Display name",
        profileEmailPlaceholder = "john@example.com",
        changePhoto = "Change photo",
        removePhoto = "Remove photo",
        saveProfile = "Save profile"
    )
    UserSettings.Language.ISIZULU -> AppStrings(
        loginTitle = "Siyakwamukela e-FitTrack SA",
        emailLogin = "Ngena nge-imeyili",
        googleSso = "Ngena nge-Google",
        biometric = "Vula nge-Biometric",
        biometricSubtitle = "Sebenzisa umunwe noma ubuso ukuqhubeka",
        biometricUnavailable = "I-biometric ayitholakali",
        biometricFailed = "I-biometric ayihambelani",
        register = "Bhalisa",
        forgotPassword = "Ukhohlwe iphasiwedi",
        dashboard = "I-Dashboard",
        activity = "Umsebenzi",
        nutrition = "Ukudla",
        progress = "Inqubekela phambili",
        settings = "Izilungiselelo",
        achievements = "Iziphumelele",
        logActivity = "Qopha Umsebenzi",
        logMeal = "Qopha Ukudla",
        viewStreaks = "Buka ama-Streaks/Iziphumelele",
        refresh = "Vuselela/Sync",
        selectType = "Khetha Uhlobo",
        setDuration = "Beka Isikhathi",
        saveActivity = "Gcina Umsebenzi",
        cancel = "Khansela",
        addFood = "Nezela Ukudla",
        useShortcut = "Sebenzisa i-Shortcut",
        saveMeal = "Gcina Ukudla",
        editDelete = "Hlela/Susa",
        weeklyMonthly = "Vikili/Nyanga",
        filterRange = "Hlunga Ibanga",
        viewDetails = "Buka Imininingwane",
        viewBadge = "Buka i-Badge",
        joinChallenge = "Joyina Inselelo",
        seeStreakDetails = "Buka ama-Streak",
        languageToggle = "Ulimi (EN/ZU)",
        notifications = "Izaziso On/Off",
        manageData = "Phatha Idatha",
        signOut = "Phuma",
        darkMode = "Itimu (Mnyama/Khanyayo)",
        profileSectionTitle = "Iphrofayela",
        profileNameLabel = "Igama olibonisayo",
        profileEmailPlaceholder = "john@example.com",
        changePhoto = "Shintsha isithombe",
        removePhoto = "Susa isithombe",
        saveProfile = "Gcina iphrofayela"
    )
}
